### ISSUE TITLE
Case for immutability

### ISSUE THREAD

**Issue by dherges** [ngrx/platform#327]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[x] Support request
</code></pre>

## What is the current behavior?

Two components are selecting the same state from the store. Draft scribble:

```ts
@Component({
  template: `{{ foo$ | async | json }}`
})
class FooComponent {
  public foo$;

  constructor (
    store: Store<State>
  ) {
    this.foo$ = store.select('something');
  }
}
```

```ts
@Component({
  template: `{{ bar$ | async | json }}`
})
class BarComponent {
  public bar$;

  constructor (
    store: Store<State>
  ) {
    this.bar$ = store.select('something');
  }
}
```

Now, say, one component (accidentally) alters the state object that was received from the store.

```ts
@Component({..})
class EvilComponent {

  constructor (
    store: Store<State>
  ) {
    store.select('something')
      .subscribe((next) => {
         next = 666; // the number of the beast :-)
      });
  }

}
```

Now, the mutation inflected by `EvilComponent` reflects through all the other components causing change detection and updating the views. Is this intended behaviour?

## Expected behavior:

Intuitively, I expected a mutation to not be possible. I thought that the state object cannot be mutated or, if mutated, a local change does not leak out to other components.

## Minimal reproduction of the problem with instructions:

See above please

## Version of affected browser(s),operating system(s), npm, node and ngrx:

```
$ node --version
v8.3.0
coala:ng-editor david$ yarn --version
n0.27.5
coala:ng-editor david$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.0-beta.0
node: 8.3.0
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.4.0-beta.0
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5
$ cat yarn.lock | grep "@ngrx"
"@ngrx/effects@^4.0.5":
  resolved "https://registry.yarnpkg.com/@ngrx/effects/-/effects-4.0.5.tgz#1224763800621b7305f9b18bc17ee09b25c861d1"
"@ngrx/router-store@^4.0.4":
  resolved "https://registry.yarnpkg.com/@ngrx/router-store/-/router-store-4.0.4.tgz#ab59f35aae93465088384faf009e21b22edd456a"
"@ngrx/store-devtools@^4.0.0":
  resolved "https://registry.yarnpkg.com/@ngrx/store-devtools/-/store-devtools-4.0.0.tgz#b79c24773217df7fd9735ad21f9cbf2533c96e04"
"@ngrx/store@^4.0.3":
  resolved "https://registry.yarnpkg.com/@ngrx/store/-/store-4.0.3.tgz#36abacdfa19bfb8506e40de80bae06050a1e15e9"
```

## Other information:

I am new to ngrx so I may not understand things fully.

I see that you [include ngrx-store-freeze in the devDependencies](https://github.com/ngrx/platform/blob/master/package.json#L97), but apparently you do not use it in the example app. When I tried to use ngrx-store-freeze in my app, it broke the devtools in Chrome (Exception message "Cannot freeze"). Looks like ngrx-store-freeze does not work w/ current versions of ngrx. Is that right?

I wonder whether it is recommended to go use immutable and [typed-immutable-record](https://github.com/rangle/typed-immutable-record) on top of ngrx to achieve immutability.

I appreciate any feedback. Same time, this issue is not neccesarily a bug. If you see it as a support request and it helps improving documentation for other users, I am fine with it!

**Comment by brandonroberts** [comment]
@dherges it works with the current version of ngrx. The reason its not being used currently was because of issues with `@ngrx/router-store`. The `RouterStateSnapshot` cannot be frozen, so `ngrx-store-freeze` was removed temporarily so users would have a better initial experience. It can be added back to the example-app since we've implemented a custom serializer for the `RouterStateSnapshot` that's "freeze-friendly".

**Comment by ssljivic** [comment]
Hi @brandonroberts , I still see errors when using ngrx-store-freeze with router-store 4.0.4. 
Which version of router-store will have custom serializer for RouterStateSnapshot that resolves the error?

**Comment by brandonroberts** [comment]
The custom serializer gives you the option to replace the default. The
default still gives you the full router state snapshot. If you look at the
router-store documentation, it provides an example of a paired down state
snapshot.

**Comment by michaeljohnbennett** [comment]
do we have an example of how to wire the store-freeze into the v4 style code? I could only see the V2 examples in the old example-app code.

I am also finding this issue with a form control that is being populated with an observable selecting from a store and I can see the mutable changes being reflected in my store again. 

Do I need to force a clone each time I read an object from the store or is there something else I'm not doing correctly?

**Comment by firecube** [comment]
Hi,

I followed the example for a custom serializer on this page https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer and I still have the error...

Cannot assign to read only property 'microTask' of object '[object Object]'

My deps are...

"@ngrx/store": "4.0.3",
"@ngrx/effects": "4.0.5",
"@ngrx/router-store": "4.0.4",
"@ngrx/store-devtools": "4.0.0",
"ngrx-store-freeze": "0.1.9",

Any pointers?

Thanks, Simon

**Comment by brandonroberts** [comment]
@firecube Did you use the exact serializer or customize it?

@michaeljohnbennett I'll be adding ngrx-store-freeze back to the example app soon. You shouldn't need to force clone the object read from the store. Can you provide an example of this form control?

**Comment by firecube** [comment]
@brandonroberts 

Thanks for getting back to me so quickly!

This is weird.  Yes, I have the same serializer code (with the addition of params as well as query params) but the problem seems to be intermittent and right now I can't get it to error.  I will keep an eye on it and reply back to this ticket if it crops up again.

**Comment by brandonroberts** [comment]
@firecube just open a new issue with a reproduction if you see it consistently.

**Comment by michaeljohnbennett** [comment]
@brandonroberts let me check with the new code and examples and see if I can get it to work, If not I'll send you over the example code.

The form control is based on the example code around book viewing from a store with some adaptations to have a single set of objects (Portfolio in my case) rather than the book/collection model in the example.

I'll update you shortly

**Comment by pscanlon1** [comment]
Im having the same issue as the OP. Is there something to get around this??

what I did as hopefully a temporary solution was to import lodash, and use deepCopy().

Ideally i don't have to do this. I am using a service in between my components and the store, and then my components subscribe to the services rather than directly to the store.

Thanks..
